#!/usr/bin/env node
/**
 * build_setup_sql.mjs — generate a single paste-ready SQL bundle for standing up
 * a NEW client's Supabase project.
 *
 * Concatenates, in order:
 *   1. every backend/db/migrations/*.sql  (the real schema — NOT backend/migrations/)
 *   2. the config seeds in backend/db/seeds/  (email/SMS templates = "same config")
 *
 * Deliberately EXCLUDES vehicle seeds — a new brand starts with an empty fleet.
 *
 * Output: backend/db/setup_new_client.sql  → paste into the Supabase SQL editor.
 * Regenerate any time migrations change:  node scripts/build_setup_sql.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const migDir = join(here, '..', 'db', 'migrations');
const seedDir = join(here, '..', 'db', 'seeds');
const outFile = join(here, '..', 'db', 'setup_new_client.sql');

// Numeric-prefix sort so 001 < 002 < … < 024 (handles the two 005_* files deterministically).
const migrations = readdirSync(migDir)
  .filter((f) => f.endsWith('.sql'))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

// Config seeds only — NO vehicles.
const seeds = ['seed_templates.sql', 'seed_rental_ops_templates.sql'];

const banner = (label) =>
  `\n\n-- ═══════════════════════════════════════════════════════════════════════\n` +
  `-- ${label}\n` +
  `-- ═══════════════════════════════════════════════════════════════════════\n`;

let out =
  `-- ============================================================================\n` +
  `-- setup_new_client.sql — GENERATED by scripts/build_setup_sql.mjs. Do not edit.\n` +
  `-- Paste into a fresh Supabase project's SQL editor to create the full schema\n` +
  `-- + config (email/SMS templates, business_settings). Empty fleet by design —\n` +
  `-- add vehicles in the dashboard after launch.\n` +
  `-- ${migrations.length} migrations + ${seeds.length} seed files.\n` +
  `-- ============================================================================\n`;

for (const f of migrations) {
  out += banner(`MIGRATION  ${f}`);
  out += readFileSync(join(migDir, f), 'utf8').trimEnd() + '\n';
}
for (const f of seeds) {
  out += banner(`SEED  ${f}`);
  out += readFileSync(join(seedDir, f), 'utf8').trimEnd() + '\n';
}

writeFileSync(outFile, out);
console.log(`Wrote ${outFile}`);
console.log(`  ${migrations.length} migrations:`, migrations.join(', '));
console.log(`  ${seeds.length} seeds:`, seeds.join(', '));
console.log(`  ${out.split('\n').length} lines total`);
