#!/usr/bin/env node
/**
 * Build a paste-ready SQL bundle for standing up a fresh Annie's Car Rental
 * Supabase database. Used by local/staging QA so seed fixtures can be proven
 * without touching production.
 *
 * Output: backend/db/setup_new_client.sql
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const dbMig = join(here, '..', 'db', 'migrations');
const feMig = join(here, '..', 'migrations');
const seeds = join(here, '..', 'db', 'seeds');
const outFile = join(here, '..', 'db', 'setup_new_client.sql');

const STEPS = [
  [dbMig, '001_initial_schema.sql', 'core schema'],
  [dbMig, '000_admin_profiles.sql', 'orphan table'],
  [feMig, '002_rental_operations.sql', 'rental ops'],
  [feMig, '003_checkin_photo_slots.sql', 'rental ops'],
  [feMig, '005_card_on_file.sql', 'rental ops'],
  [feMig, '022_create_brands.sql', 'brands'],
  [dbMig, '002_add_stripe.sql', 'migration'],
  [dbMig, '003_add_id_photo.sql', 'migration'],
  [dbMig, '004_rental_agreements.sql', 'migration'],
  [dbMig, '005_006_new_tables.sql', 'migration'],
  [dbMig, '005_notifications.sql', 'migration'],
  [dbMig, '007_message_templates.sql', 'migration'],
  [dbMig, '008_weekly_monthly_pricing.sql', 'migration'],
  [dbMig, '009_bonzah_integration.sql', 'migration'],
  [dbMig, '010_terminal_return_date_invariant.sql', 'migration'],
  [dbMig, '011_checkout_override.sql', 'migration'],
  [dbMig, '012_notification_log.sql', 'migration'],
  [dbMig, '013_sms_opt_out.sql', 'migration'],
  [dbMig, '014_orphan_stage_cleanup.sql', 'migration'],
  [dbMig, '015_one_active_template_per_stage.sql', 'migration'],
  [dbMig, '016_conversation_summaries_view.sql', 'migration'],
  [dbMig, '017_bouncie_integration.sql', 'migration'],
  [dbMig, '018_business_settings.sql', 'migration'],
  [dbMig, '019_trusted_customers.sql', 'migration'],
  [dbMig, '020_template_timing.sql', 'migration'],
  [dbMig, '021_voice_hunt_group.sql', 'migration'],
  [dbMig, '022_unify_business_phone.sql', 'migration'],
  [dbMig, '023_push_subscriptions.sql', 'migration'],
  [dbMig, '024_admin_push_subscriptions.sql', 'migration'],
  [dbMig, '023_rental_extensions.sql', 'migration'],
  [dbMig, '024_payment_plans.sql', 'migration'],
  [dbMig, '025_admin_booking_prefill.sql', 'migration'],
  [dbMig, '026_team_alert_phones.sql', 'migration'],
  [dbMig, '027_portal_long_term.sql', 'migration'],
  [dbMig, '028_booking_customer_data_capture.sql', 'migration'],
  [dbMig, '029_approval_high_risk.sql', 'migration'],
  [seeds, '00_email_templates_stage_unique.sql', 'pre-seed constraint'],
  [seeds, 'seed_templates.sql', 'seed'],
  [seeds, 'seed_rental_ops_templates.sql', 'seed'],
  [dbMig, '014_orphan_stage_cleanup.sql', 'post-seed'],
  [dbMig, '015_one_active_template_per_stage.sql', 'post-seed'],
  [dbMig, '020_template_timing.sql', 'post-seed'],
  [feMig, '004_vehicle_transparency_templates.sql', 'post-seed'],
  [seeds, '99_grants.sql', 'grants'],
];

const banner = (label, file) =>
  `\n\n-- ============================================================================\n` +
  `-- [${label}] ${file}\n` +
  `-- ============================================================================\n`;

let out =
  `-- ============================================================================\n` +
  `-- setup_new_client.sql - GENERATED by scripts/build_setup_sql.mjs. Do not edit.\n` +
  `-- Builds the Annie's Car Rental schema and message/template config for a\n` +
  `-- fresh local or staging Supabase database.\n` +
  `-- ============================================================================\n`;

for (const [dir, file, label] of STEPS) {
  out += banner(label, file);
  out += readFileSync(join(dir, file), 'utf8').trimEnd() + '\n';
}

writeFileSync(outFile, out);
console.log(`Wrote ${outFile}`);
console.log(`  ${STEPS.length} steps, ${out.split('\n').length} lines`);
