-- Email-copy redesign (2026-06) — Annie's Car Rental
-- Idempotent UPSERT. Does NOT delete; only refreshes the 23 stages below.
-- Generated by db/seeds/redesign_email_copy.mjs. Review before running.
-- Apply against the brand's OWN Supabase project (verify SUPABASE_URL first).

BEGIN;

-- Booking Submitted
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Booking Submitted', E'booking_submitted', E'both',
  E'Request received — {{booking_code}}',
  E'Hi {{first_name}},\n\nThanks for choosing Annie''s Car Rental. We''ve got your request and we''re reviewing it now — you''ll hear back within a few hours during business hours.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nPickup: {{pickup_date}} at {{pickup_time}}\nReturn: {{return_date}} at {{return_time}}\nTotal: ${{total_cost}}\n\nOnce we confirm availability, we''ll send a link to sign your agreement and pay.\n\nQuestions? Call or text (772) 207-1655.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Thanks {{first_name}} — we''ve got your request with Annie''s Car Rental.\n\n{{vehicle}}\n{{pickup_date}} – {{return_date}}\nRef {{booking_code}}\n\nWe''ll confirm within a few hours. — Annie''s Car Rental',
  E'automated', E'Sent immediately when a customer submits a booking request.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Booking Approved
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Booking Approved', E'booking_approved', E'both',
  E'You’re confirmed — {{vehicle}} ({{booking_code}})',
  E'Hi {{first_name}},\n\nYou''re confirmed. Sign your agreement and pay to lock it in — that''s the only step left.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nPickup: {{pickup_date}} at {{pickup_time}}\nReturn: {{return_date}} at {{return_time}}\nMileage: {{mileage_policy}}\nTotal: ${{total_cost}}\n\nWe''ll text your exact address, parking spot, and lockbox code 24 hours before pickup. Prefer delivery? Just reply and we''ll set it up.\n\nQuestions? Call or text (772) 207-1655.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'You''re confirmed, {{first_name}}!\n\n{{vehicle}}\nPickup {{pickup_date}} at {{pickup_time}}\nRef {{booking_code}}\n\nSign & pay to lock it in: {{confirm_link}}\n\nWe''ll text pickup details the day before. — Annie''s Car Rental',
  E'automated', E'Sent when the admin approves a booking request.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Booking Declined
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Booking Declined', E'booking_declined', E'both',
  E'About your booking request — {{booking_code}}',
  E'Hi {{first_name}},\n\nUnfortunately we can''t confirm this booking.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nDates: {{pickup_date}} – {{return_date}}\n\nWhy: {{decline_reason}}\n\nWe may have another vehicle open for your dates. Call us at (772) 207-1655 and we''ll find you something that works.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, we couldn''t confirm the {{vehicle}} for {{pickup_date}}–{{return_date}}.\n\n{{decline_reason}}\n\nCall (772) 207-1655 and we''ll find an alternative. — Annie''s Car Rental',
  E'automated', E'Sent when the admin declines a booking request.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Payment Confirmed
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Payment Confirmed', E'payment_confirmed', E'both',
  E'Payment received — you’re all set ({{booking_code}})',
  E'Hi {{first_name}},\n\nPayment received and your booking is confirmed. Your receipt and pickup steps are below.\n\nEverything lives in your portal — receipt, check-in, messages, and extensions. {{#if deposit_amount}}Your ${{deposit_amount}} deposit is fully refundable and returns 3–5 business days after inspection.{{/if}}\n\nQuestions? Call or text (772) 207-1655.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Payment confirmed, {{first_name}} — you''re all set!\n\n{{vehicle}}\nPickup {{pickup_date}} at {{pickup_time}}\nRef {{booking_code}}\n\nYour portal: {{portal_link}}\nWe''ll text pickup details the day before. — Annie''s Car Rental',
  E'automated', E'Sent when a payment succeeds. Itemized receipt + pickup steps are added automatically above this body.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Payment Reminder
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Payment Reminder', E'payment_reminder', E'both',
  E'Complete your booking — {{booking_code}}',
  E'Hi {{first_name}},\n\nYour {{vehicle}} is reserved, but we still need your agreement and payment to lock it in.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nPickup: {{pickup_date}} at {{pickup_time}}\nTotal: ${{total_cost}}\n\nUnpaid bookings expire 48 hours after approval. It only takes a few minutes to finish.\n\nQuestions? Call or text (772) 207-1655.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your {{vehicle}} is reserved — payment still needed.\n\nRef {{booking_code}}\nPickup {{pickup_date}} at {{pickup_time}}\n\nFinish here: {{confirm_link}}\nUnpaid bookings expire 48h after approval. — Annie''s Car Rental',
  E'automated', E'Sent 24 hours after approval when payment has not been completed.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Insurance Approved
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Insurance Approved', E'insurance_approved', E'both',
  E'Insurance approved — you’re all set ({{booking_code}})',
  E'Hi {{first_name}},\n\nYour insurance documents are approved. You''re cleared for pickup.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nPickup: {{pickup_date}} at {{pickup_time}}\n\nWe''ll text your exact address and lockbox code 24 hours before pickup.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your insurance is approved for {{booking_code}}. You''re cleared for pickup {{pickup_date}}.\n\nDetails: {{portal_link}} — Annie''s Car Rental',
  E'automated', E'Sent when admin approves own-insurance documents.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Insurance Rejected
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Insurance Rejected', E'insurance_rejected', E'both',
  E'Insurance needs attention — {{booking_code}}',
  E'Hi {{first_name}},\n\nWe reviewed your insurance documents and need updated information before your rental.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nPickup: {{pickup_date}} at {{pickup_time}}\n\nPlease upload corrected documents in your portal, or call us at (772) 207-1655 and we''ll help.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, we need updated insurance docs for {{booking_code}} before pickup.\n\nUpload in your portal: {{portal_link}}\nOr call (772) 207-1655. — Annie''s Car Rental',
  E'automated', E'Sent when admin rejects own-insurance documents.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Ready for Pickup
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Ready for Pickup', E'ready_for_pickup', E'both',
  E'Your {{vehicle}} is ready — {{booking_code}}',
  E'Hi {{first_name}},\n\nYour vehicle is cleaned, prepped, and ready.\n\nVehicle: {{vehicle}}\nReference: {{booking_code}}\nPickup: {{pickup_date}} at {{pickup_time}}\n\nGetting your keys\n1234 SE Commerce Ave, Port St. Lucie, FL 34952 — park and walk to the back of the building. Your vehicle has a key lockbox on the window. Enter code {{lockbox_code}}, take the key, and remove the lockbox before driving.\n\nA few house rules: return with the same fuel level, no smoking, no pets ($150 cleaning fee each). Text us when you arrive.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your {{vehicle}} is ready for pickup.\n\n1234 SE Commerce Ave, Port St. Lucie, FL 34952 (back of building)\nLockbox code {{lockbox_code}}\n\nCheck in: {{status_link}}\nHave a great trip! — Annie''s Car Rental',
  E'automated', E'Sent when admin marks a vehicle as ready for pickup.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Pre-Pickup Reminder
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Pre-Pickup Reminder', E'pickup_reminder', E'both',
  E'Pickup tomorrow — your {{vehicle}} is ready ({{booking_code}})',
  E'Hi {{first_name}},\n\nYour rental starts tomorrow. Here''s everything you need.\n\nPickup: {{pickup_date}} at {{pickup_time}}\nVehicle: {{vehicle}}\nReference: {{booking_code}}\nMileage: {{mileage_policy}}\n\nGetting your keys\n1234 SE Commerce Ave, Port St. Lucie, FL 34952 — park and walk to the back of the building. Your vehicle has a key lockbox on the window. Enter code {{lockbox_code}}, take the key, and remove the lockbox before driving.\n\nA few house rules: return with the same fuel level, no smoking, no pets ($150 cleaning fee each). Text us when you arrive.\n\nQuestions? Call or text (772) 207-1655.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your {{vehicle}} is ready for pickup tomorrow.\n\nMileage: {{mileage_policy}}\n1234 SE Commerce Ave, Port St. Lucie, FL 34952\nLockbox code {{lockbox_code}} (car parked in back)\n\n1. Go to the back of the building\n2. Find the car with the lockbox on the window\n3. Enter {{lockbox_code}}, take the key, remove the lockbox\n\nCheck in: {{portal_link}}\nNeed help? (772) 207-1655 — Annie''s Car Rental',
  E'automated', E'Sent automatically 24 hours before the pickup date.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Day-of Pickup
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Day-of Pickup', E'day_of_pickup', E'sms',
  '',
  '',
  E'Good morning, {{first_name}}! Your {{vehicle}} is ready for pickup today at {{pickup_time}}.\n\n1234 SE Commerce Ave, Port St. Lucie, FL 34952 (back of building)\nLockbox code {{lockbox_code}}\n\nCheck in: {{portal_link}}\nDrive safe — text us if anything comes up. — Annie''s Car Rental, (772) 207-1655',
  E'automated', E'Sent the morning of the pickup date.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Mid-Rental Check-in
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Mid-Rental Check-in', E'mid_rental_checkin', E'sms',
  '',
  '',
  E'Hi {{first_name}}, just checking in — how''s the {{vehicle}} treating you?\n\nYour return is set for {{return_date}}. Want to keep it longer? Reply and we''ll hold it for you, no rebooking needed.\n\n— Annie''s Car Rental, (772) 207-1655',
  E'automated', E'Sent partway through longer rentals.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Pre-Return Reminder
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Pre-Return Reminder', E'return_reminder', E'both',
  E'Return reminder — {{vehicle}} due {{return_date}}',
  E'Hi {{first_name}},\n\nYour rental is almost up. A quick checklist for a smooth return.\n\nReturn: {{return_date}} at {{return_time}}\nVehicle: {{vehicle}}\nReference: {{booking_code}}\n\nBefore you drop off: refill fuel to the level you received, park in the back near the dumpster, return the key to the lockbox (code {{lockbox_code}}), and snap a photo of where you parked.\n\nPlans changed? Reply and we''ll check on extending your rental.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your {{vehicle}} is due back tomorrow by {{return_time}}.\n\n1234 SE Commerce Ave, Port St. Lucie, FL 34952\n\nBefore drop-off:\n• Same fuel level as pickup\n• Park in back, near the dumpster\n• Key in lockbox (code {{lockbox_code}})\n• Photo of where you parked\n\nWant to extend? Reply and we''ll check. — Annie''s Car Rental',
  E'automated', E'Sent automatically 24 hours before the return date.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Day-of Return
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Day-of Return', E'day_of_return', E'sms',
  '',
  '',
  E'Good morning, {{first_name}}! Your {{vehicle}} is due back today by {{return_time}}.\n\n1234 SE Commerce Ave, Port St. Lucie, FL 34952 (back of building, near the dumpster)\nKey in lockbox (code {{lockbox_code}})\n\nQuick checklist:\n• Same fuel level as pickup\n• Photo of where you parked\n• Reply to extend if plans changed\n\nThanks again! — Annie''s Car Rental, (772) 207-1655',
  E'automated', E'Sent the morning of the return date.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Return Confirmed
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Return Confirmed', E'return_confirmed', E'sms',
  '',
  '',
  E'Hi {{first_name}}, we''ve got the {{vehicle}} back and everything looks great. Thanks for taking care of it.\n\nHope to see you again soon! — Annie''s Car Rental',
  E'manual', E'Sent after the vehicle is returned and inspected.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Rental Completed
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Rental Completed', E'rental_completed', E'both',
  E'How was your {{vehicle}}, {{first_name}}?',
  E'Hi {{first_name}},\n\nThanks for renting with Annie''s Car Rental — we hope the {{vehicle}} made your trip easier.\n\nIf you have a moment, a quick review means a lot. As a thank-you, you''ll get 5% off your next rental — just mention it when you book.\n\nWe''d love to have you back.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, hope you enjoyed your {{vehicle}}!\n\nA quick review would mean a lot — and we''ll take 5% off your next rental as thanks.\n\n{{review_link}}\n— Annie''s Car Rental',
  E'automated', E'Sent the day after return — review request.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Late Return Warning
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Late Return Warning', E'late_return_warning', E'sms',
  '',
  '',
  E'Hi {{first_name}}, your {{vehicle}} was due back at {{return_time}} today. On your way? Just send your ETA.\n\nNeed more time? Reply and we''ll check on extending.\n\nReturn: 1234 SE Commerce Ave, Port St. Lucie, FL 34952\n— Annie''s Car Rental, (772) 207-1655',
  E'automated', E'Sent on the first day after the scheduled return date.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Late Return Escalation
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Late Return Escalation', E'late_return_escalation', E'both',
  E'Your rental is overdue — {{booking_code}}',
  E'{{first_name}},\n\nYour {{vehicle}} was due back today at {{return_time}} and hasn''t been returned. We''ve also been unable to reach you.\n\nReference: {{booking_code}}\nDue: {{return_date}} at {{return_time}}\nStatus: Overdue\n\nPlease return the vehicle to 1234 SE Commerce Ave, Port St. Lucie, FL 34952 right away, or call us at (772) 207-1655. Late fees apply to overdue rentals. If there''s an emergency, let us know and we''ll work with you.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'{{first_name}}, your {{vehicle}} was due back at {{return_time}} today and hasn''t been returned.\n\nPlease return it now or call (772) 207-1655. Late fees apply to overdue rentals.\n\n— Annie''s Car Rental',
  E'automated', E'Sent 4 days after the scheduled return date.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Extension Offer
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Extension Offer', E'extension_offer', E'sms',
  '',
  '',
  E'Hi {{first_name}}, your rental ends {{return_date}}. Enjoying the {{vehicle}}? We can extend it.\n\nReply with how many extra days you need and we''ll confirm pricing and availability.\n\n— Annie''s Car Rental',
  E'automated', E'Sent before the return date for multi-day rentals.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Damage Notification
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Damage Notification', E'damage_notification', E'email',
  E'A note about your recent rental — {{booking_code}}',
  E'Hi {{first_name}},\n\nWe wanted to reach out about your recent rental of the {{vehicle}} ({{booking_code}}). During our post-rental inspection we noted some damage we''ll need to follow up on.\n\nWhat we found: {{damage_description}}\n\nWe''ll review the details and contact you within one business day to walk through what we found, whether anything is owed beyond your deposit, and answer any questions.\n\nWant to get ahead of it? Reach us at (772) 207-1655, or view your booking in the portal.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  '',
  E'manual', E'Sent after inspection reveals damage.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Deposit Refunded
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Deposit Refunded', E'deposit_refunded', E'both',
  E'Your ${{deposit_amount}} deposit is on its way back — {{booking_code}}',
  E'Hi {{first_name}},\n\nGood news — your security deposit has been fully refunded.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nDeposit held: ${{deposit_amount}}\nRefunded: ${{refund_amount}}\n\nIt''ll appear on your original payment method within 5–10 business days. Thanks for taking great care of the vehicle — we hope to see you again.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your ${{deposit_amount}} deposit for the {{vehicle}} has been fully refunded.\n\nRef {{booking_code}}\nExpect it within 5–10 business days. — Annie''s Car Rental',
  E'automated', E'Sent when a security deposit is fully refunded.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Deposit Settled
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Deposit Settled', E'deposit_settled', E'both',
  E'Deposit settlement — {{booking_code}}',
  E'Hi {{first_name}},\n\nYour security deposit has been settled. Here''s the breakdown.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nDeposit held: ${{deposit_amount}}\nCharges applied: ${{incidental_total}}\nRefund: ${{refund_amount}}\n\n{{#if refund_amount}}Your ${{refund_amount}} refund returns to your original payment method within 5–10 business days.{{/if}} Questions about a charge? Reach us at (772) 207-1655, or review and dispute it in your portal.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your deposit for the {{vehicle}} is settled.\n\nDeposit ${{deposit_amount}} · Charges ${{incidental_total}} · Refund ${{refund_amount}}\nRef {{booking_code}}\n\nRefund arrives in 5–10 business days. Questions? (772) 207-1655 — Annie''s Car Rental',
  E'automated', E'Sent when a deposit is settled against incidentals.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Repeat Customer
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Repeat Customer', E'repeat_customer', E'email',
  E'{{first_name}}, your next rental is 5% off',
  E'Hi {{first_name}},\n\nThanks for renting with Annie''s Car Rental. As a returning guest, here''s 5% off your next trip — just mention this email when you book.\n\nWe''re always adding vehicles and sharpening the experience. Whenever you need a car next, we''d love to have you back.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  '',
  E'automated', E'Sent a while after rental completion.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

-- Booking Cancelled
INSERT INTO email_templates (name, stage, channel, subject, body, sms_body, trigger_type, description) VALUES (
  E'Booking Cancelled', E'booking_cancelled', E'both',
  E'Booking cancelled — {{booking_code}}',
  E'Hi {{first_name}},\n\nYour booking has been cancelled.\n\nReference: {{booking_code}}\nVehicle: {{vehicle}}\nDates: {{pickup_date}} – {{return_date}}\n\nAny deposit collected is refunded to your original payment method within 3–5 business days. Want to rebook? We''re here at (772) 207-1655.\n\nAnnie''s Car Rental\nPort St. Lucie, FL',
  E'Hi {{first_name}}, your booking for the {{vehicle}} ({{pickup_date}}–{{return_date}}) is cancelled.\n\nRef {{booking_code}}\nAny deposit is refunded within 3–5 business days.\n\nQuestions? (772) 207-1655 — Annie''s Car Rental',
  E'automated', E'Sent when a booking is cancelled.'
)
ON CONFLICT (stage) DO UPDATE SET
  name = EXCLUDED.name, channel = EXCLUDED.channel, subject = EXCLUDED.subject,
  body = EXCLUDED.body, sms_body = EXCLUDED.sms_body,
  trigger_type = EXCLUDED.trigger_type, description = EXCLUDED.description;

COMMIT;

SELECT stage, channel FROM email_templates WHERE stage IN ('booking_submitted', 'booking_approved', 'booking_declined', 'payment_confirmed', 'payment_reminder', 'insurance_approved', 'insurance_rejected', 'ready_for_pickup', 'pickup_reminder', 'day_of_pickup', 'mid_rental_checkin', 'return_reminder', 'day_of_return', 'return_confirmed', 'rental_completed', 'late_return_warning', 'late_return_escalation', 'extension_offer', 'damage_notification', 'deposit_refunded', 'deposit_settled', 'repeat_customer', 'booking_cancelled') ORDER BY stage;
